language: java

jdk:
  - openjdk8

env:
  - MAVEN_OPTS=-B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

cache:
  directories:
    - .autoconf
    - $TRAVIS_HOME/.m2

services:
  - docker
  - rabbitmq
  - postgresql

before_install:
  - "sudo apt-get install graphviz"

install: true

before_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres
  - psql -c "CREATE USER karl WITH PASSWORD 'karl';" -U postgres

addons:
  sonarcloud:
    organization: "openwms-github"
  postgresql: '9.6'

script:
  - if [[ ( "$TRAVIS_BRANCH" != "master" ) ]]; then mvn $MAVEN_OPTS package -DsurefireArgs=-Dspring.profiles.active=ASYNCHRONOUS,TEST -Dci.buildNumber=$TRAVIS_BUILD_NUMBER -U; fi
  - if [[ ( "$TRAVIS_BRANCH" == "master" ) ]]; then mvn $MAVEN_OPTS clean package sonar:sonar -DsurefireArgs=-Dspring.profiles.active=ASYNCHRONOUS,TEST -Dmaven.test.error.ignore=true -Dmaven.test.failure.ignore=true -Dci.buildNumber=$TRAVIS_BUILD_NUMBER -Psonar; fi
  - if [[ ( "$TRAVIS_BRANCH" == "master" ) ]]; then mvn $MAVEN_OPTS site scm-publish:publish-scm -DsurefireArgs=-Dspring.profiles.active=ASYNCHRONOUS,TEST,TESTPG -Denforcer.skip=true -Dscmpublish.pubScmUrl=scm:git:https://${PUSHKEY}@github.com/openwms/org.openwms.tms.routing.git -DdeveloperConnectionUrl=scm:git:https://${PUSHKEY}@github.com/openwms/org.openwms.tms.routing.git -Dci.buildNumber=$TRAVIS_BUILD_NUMBER -Pschemagen; fi
  - if [[ ( "$TRAVIS_BRANCH" == "master" ) ]]; then mvn $MAVEN_OPTS clean package -Denforcer.skip=true -DskipTests=true -Dci.buildNumber=$TRAVIS_BUILD_NUMBER -Prelease,gpg; fi

after_success:
  - docker build -t openwms/org.openwms.tms.routing:latest .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master