eureka:
  client:
    healthcheck:
      enabled: true

owms:
  partners:
    sps01: osip.res.1
    sps02: osip.res.2
    sps03: osip.res.3

---
spring:
  profiles: ASYNCHRONOUS

owms:
  driver:
    osip:
      enabled: true
      err:
        queue-name: tms-rtng-err
        exchange-name: osip
        routing-key-in: osip.err.ss
        routing-key-out: osip.err.mfc
      locu:
        queue-name: tms-rtng-locu
        exchange-name: osip
        routing-key-in: osip.locu.ss
      sysu:
        queue-name: tms-rtng-sysu
        exchange-name: osip
        routing-key-in: osip.sysu.ss
      req:
        queue-name: tms-rtng-req
        exchange-name: osip
        routing-key-in: osip.req.ss
      res:
        exchange-name: osip
      upd:
        queue-name: tms-rtng-upd
        exchange-name: osip
        routing-key-in: osip.upd.ss
      updx:
        queue-name: tms-rtng-updx
        exchange-name: osip
        routing-key-in: osip.updx.ss
  routing:
    serialization: json
  commands:
    common:
      tu:
        exchange-name: common.tu.commands
        routing-key: common.tu.command.asNextLocation
  requests:
    tms:
      to:
        exchange-name: tms.requests
    routing:
      to:
        exchange-name: routing.requests
        queue-name: routing-requests-queue
        routing-key: "*.*.*"

health:
  config:
    enabled: true
